# -*- coding: utf-8 -*-
"""Copia de lab2gutierrez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ccfn7Q4GVhtHw3QCuMXulVI3Bn3PlwID
"""

from google.colab import drive
drive.mount('/content/drive')

# Paso 1
import pandas as pd

path = "/content/drive/MyDrive/base de datos/atenciones_abogadas_de_las_mujeres.csv"

df = pd.read_csv(path)


# Registros

registros = df.shape[0]

print (registros)

# Paso 2

df.info()

# Paso 3

df.tail(1)

# Paso 4 "OObtener el rangop de fechas"

df["fecha"]=pd.to_datetime(df["fecha"], format="%Y-%m-%d")

fecha_inicial = df ["fecha"].min()

fecha_final= df["fecha"].max()

print(f"El rango de fecha es del {fecha_inicial} al {fecha_final}")

#Paso 5 "Obtener la media aritmética"

media = df["usuaria_edad"].mean()

print(media)

#Paso 6 "Obtener la moda"

moda = df["usuaria_edad"].mode()

print(moda)